excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Game ListTests
  - Game ListUITests
  - .build
line_length: 200
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
  allowed_symbols:
    - _
reporter: "xcode"
superfluous_disable_command: warning
